#file: noinspection undefined
spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10