services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
