#file: noinspection undefined
server:
  port: 0
spring:
  application:
    name: aggregator
kafka:
  bootstrap-server: localhost:9092
  group-id: aggregator
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1
  consumer:
    attempt-timeout: 1000