#file: noinspection undefined
server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6434/userdb
    username: postgres
    password: postgres

logging:
  level:
    org.hibernate.SQL: INFO
