server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: categories_event_service_routes
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**
        - id: compilation_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**,/compilations/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/users/{userId}/events,/users/{userId}/events/{eventId},/events, /events/{eventId}
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests
        - id: comment_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/{eventId}/comments/**,/admin/comments/**,/users/{userId}/events/{eventId}/comments/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: INFO